// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const chatLog: string;
export const chatContainer: string;
export const inputControls: string;
